ktor:
  deployment:
    port: 8080
  application:
    modules:
      - com.frolova.SerializationKt.configureSerialization
      - com.frolova.StatusPagesKt.configureStatusPages
      - com.frolova.ResourcesKt.configureResources
      - com.frolova.RoutingKt.configureRouting
